### ISSUE TITLE
Unable to copy Tarantool version from graphics

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/microb#1]
I want to do `git checkout 1.6.6-xxx-yy` to check the code, but I can't copy this revision directly from microb site.

**Comment by Sulverus** [comment]
You can copy it from uri/query string, version numbers updated automatically with js

**Comment by Sulverus** [comment]
Done. You can click in chart vertexes and view git command helper
![checkout](https://cloud.githubusercontent.com/assets/1609170/13443935/8a7f0bc8-e014-11e5-8b1c-ab6d66044a30.png)

Live link:
http://sh5.tarantool.org/?first=1.6.8-517-gdf18794&last=1.6.8-535-g1a3f8ba&tab=tab-nosqlbench.hash
