### ISSUE TITLE
Fix errors, caused by new tarantool version

### ISSUE THREAD

**Issue by iproha94** [tarantool/microb#14]
Example errors:
* ` main/101/start_storage.lua schema.lua:561 W> field type 'num' is deprecated since Tarantool 1.7, please use 'unsigned' instead `
* ` main/108/http/127.0.0.1:46348 server.lua:677 E> unhandled error: builtin/box/schema.lua:1107: bad argument #1 to 'insert' (table expected, got string) `
* ` main/109/http/127.0.0.1:46596 server.lua:677 E> unhandled error: ./microb/web.lua:192: assign to undeclared variable 'metric_id' `
* ` main/110/http/127.0.0.1:47538 server.lua:677 E> unhandled error: ./microb/web.lua:91: variable 'ALL' is not declared `
* ` main/111/http/127.0.0.1:47540 server.lua:677 E> unhandled error: Supplied key type of part 0 does not match index part type: expected unsigned `
* if push with new METRIC_NAME, then
```
Unhandled error: builtin/box/schema.lua:1348: bad argument #1 to 'insert' (table expected, got string)
stack traceback:
	/usr/local/share/lua/5.1/http/server.lua:675: in function 'process_client'
	/usr/local/share/lua/5.1/http/server.lua:1113: in function </usr/local/share/lua/5.1/http/server.lua:1113>
	[C]: in function 'pcall'
	builtin/socket.lua:997: in function <builtin/socket.lua:995>

```

**Comment by iproha94** [comment]
fix in `iproha94/gh-14-fix-errors` branch

**Comment by LaserPhaser** [comment]
Merged
