### ISSUE TITLE
please add nosqlbench.sophia

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/microb#3]

**Comment by bigbes** [comment]
Please, attach custom config file to test with.

With best regards, Eugene.

2016-02-26 16:02 GMT+03:00 Dmitry Simonenko notifications@github.com:

**Comment by pmwkaa** [comment]
can you use exactly the same as for nosqlbench.tree? to have a direct comparison

**Comment by bigbes** [comment]
Ok

2016-02-26 16:33 GMT+03:00 Dmitry Simonenko notifications@github.com:

> can you use exactly the same as for nosqlbench.tree? to have a direct
> comparison

With best regards, Eugene.

**Comment by bigbes** [comment]
http://sh5.tarantool.org/?first=1.6.8-529-g604c75c&last=1.6.8-530-g9c48ea8
Added.
