### ISSUE TITLE
Integrate cbench to microb

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/microb#4]
cbench is now a Lua module:
https://github.com/tarantool/cbench

Please add cbench results to microb.
I'm primary interested in multi-part keys benchmarks 1.6.7-last vs 1.6.8-530.

**Comment by Sulverus** [comment]
Implemented in https://github.com/tarantool/cbench/commit/d0153fb98385ae8fd8b67cdec912694263d4f54a

Deployed in sh5.tarantool.org (http://sh5.tarantool.org/?first=1.6.8-579-gb90c981&last=1.6.8-583-gd52bda2&tab=tab-cbench.hash_num). Totaly we have 6 \* 12 workloads, so I divided it into 12 tabs with 6 charts.
