### ISSUE TITLE
Update URI when selecting From and To

### ISSUE THREAD

**Issue by kostja** [tarantool/microb#5]
Changes of both From and To should be reflected in the URI. Provide # links inside the page, so that a single chart can be referenced. The extended URI should load the charts in the passed range only.

**Comment by Sulverus** [comment]
Updated. Single chart and tab selection can be referenced. Example with 1.6.8 changes in nosqlbench.hash:
http://sh5.tarantool.org/?first=1.6.8-451-g399c1ef&last=1.6.8-494-g64f832c&tab=tab-nosqlbench.hash
